
[window]
opacity = 0.8
padding.x = 10
padding.y = 10
dynamic_padding = true

[font]
normal.family = "JetBrains Mono"
normal.style = "Regular"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"

[general]
import = [
  "~/.config/alacritty/themes/themes/midnight-haze.toml"
]

