# Nvidia + wayland stuff
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

monitor=HDMI-A-1, 1920x1080, 0x0, 1
monitor=DP-2, 2560x1440@165, 1920x0, 1
