# Nvidia + wayland stuff
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

monitor=HDMI-A-1, 1920x1080, 0x0, 1
monitor=DP-2, 2560x1440@165, 1920x0, 1

# =========
exec-once = wayvnc 0.0.0.0

monitor=HEADLESS,2560x1440@60,3840x1920,1

# <===== how to enable VNC
#1. Comment next line
monitor=HEADLESS, disable

#3 Uncomment next lines
# monitor=HDMI-A-1, disable
# monitor=DP-2,disable

# =====>
