monitor= , preferred, auto, auto

monitor=HEADLESS,2560x1440@60,3840x1920,1

# <===== how to enable VNC (inverse for disabling)
#1. Comment next line
monitor=HEADLESS, disable

#3 Uncomment next lines
# monitor=HDMI-A-1, disable
# monitor=DP-2,disable

# =====>

exec-once = wayvnc 127.0.0.1

workspace = 1, monitor:HDMI-A-4, default:true
workspace = 2, monitor:HDMI-A-4
workspace = 3, monitor:HDMI-A-4
workspace = 4, monitor:HDMI-A-4
workspace = 5, monitor:HDMI-A-4
workspace = 6, monitor:HDMI-A-1
workspace = 7, monitor:HDMI-A-1
workspace = 8, monitor:HDMI-A-1, default:true
workspace = 9, monitor:HDMI-A-1
workspace = 10, monitor:HDMI-A-1

exec-once = hyprctl dispatch exec [workspace 1 silent] firefox
exec-once = hyprctl dispatch exec [workspace 2 silent] slack 
exec-once = hyprctl dispatch exec [workspace 8 silent] alacritty 
exec-once = hyprctl dispatch exec [workspace 9 silent] ~/.local/share/JetBrains/Toolbox/apps/rider/bin/rider ~/git/ngSneleentaxi/Sneleentaxi.sln

windowrule {
  name = firefox
  match:class = firefox

  workspace = 1
}

windowrule {
  name = slack
  match:class = slack

  workspace = 2
}

windowrule {
  name = alacritty
  match:class = alacritty

  workspace = 8
}

windowrule {
  name = rider
  match:class = jetbrains-rider

  workspace = 9
}


